In [1]:
path = (
    '/home/maciej/Downloads/part-00000-tid-3547456983017321299-'
    'ad504ef8-3e99-473d-81a1-5809d95d8aec-27838-c000.gz.parquet')

In [2]:
import pandas as pd

In [3]:
df = pd.read_parquet(path)

In [4]:
df.head(10)

,timestamp_client,property,value,source,year,month,day
0,2019-01-23T17:26:06.423Z,heating.circuits.0.sensors.temperature.supply/...,57,dc,2019,1,23
1,2019-01-23T17:27:58.539Z,heating.circuits.0.sensors.temperature.supply/...,58,dc,2019,1,23
2,2019-01-23T16:31:13.965Z,heating.circuits.0.sensors.temperature.supply/...,58,dc,2019,1,23
3,2019-01-23T16:33:36.326Z,heating.circuits.0.sensors.temperature.supply/...,57,dc,2019,1,23
4,2019-01-23T10:54:11.532Z,heating.sensors.temperature.outside/value,-3,dc,2019,1,23
5,2019-01-23T07:28:26.476Z,heating.dhw.sensors.temperature.hotWaterStorag...,48.2,dc,2019,1,23
6,2019-01-23T11:03:12.562Z,heating.sensors.temperature.outside/value,-2.8,dc,2019,1,23
7,2019-01-23T14:56:53.549Z,heating.circuits.0.sensors.temperature.supply/...,57,dc,2019,1,23
8,2019-01-23T14:57:33.806Z,heating.boiler.temperature/value,57.2,dc,2019,1,23
9,2019-01-23T02:53:43.994Z,heating.circuits.0.sensors.temperature.supply/...,50,dc,2019,1,23

In [5]:
df.count()

timestamp_client    177902
property            177902
value               177902
source              177902
year                177902
month               177902
day                 177902
dtype: int64